### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mickel8** [elixir-webrtc/ex_webrtc#28]
# 0.1.0 (01.2024)
### Media reading/writing:
* [x] IVF reader/writer - #29 #44
* [x] Ogg reader/writer - #43 #50
* [x] VP8 RTP packetizer/depacketizer - #30 #45
* [x] Opus RTP packetize/depacketizer - #47 #53
* [x] Sending from a file (without RTCP) - #30 #37 #39

### `PeerConnection` API:
* [x] Closing PeerConnection #40
* [x] Renegotiation - #55 #59
* [x] addTrack #38
* [x] removeTrack #49
* [x] Stopping transceivers #55
* [x] Tests for failing negotiation because of unsupported codecs - #48 #61

### Documentation:
* [x] Documentation and typespec improvements - #57
* [x] Transceiver guide - #56

# 0.2.0 (04.2024)

* [x] Initial benchmarks https://github.com/elixir-webrtc/bench/pull/1

### RTCP related:
* [x] RTCP Sender and Receiver Reports - #77 #78 #81
* [x] TWCC Feedbacks - #63
* [x] NACKs and RTX - #90 #101

### ICE features:
* [x] ICE mDNS (client-side) https://github.com/elixir-webrtc/ex_ice/pull/28 https://github.com/elixir-webrtc/ex_ice/pull/27
* [x] ICE relay candidates elixir-webrtc/ex_ice#33

# 0.3.0 (07.2024)

* [x] Inbound Simulcast #111
* [x] Benchmarks and profiling

## UX improvements/features:
* [x] User-friendly media/codec/extension configuration #120
* [x] ICE port range configuration https://github.com/elixir-webrtc/ex_ice/pull/43
* ~Better logs~

### [Fishjam](https://github.com/jellyfish-dev/jellyfish):
* ~Experimental WebRTC Endpoint using Elixir WebRTC~

### [Broadcaster](https://github.com/elixir-webrtc/apps/tree/master/broadcaster) improvements:
* [x] Viewer count https://github.com/elixir-webrtc/apps/pull/12
* ~Client-side ICE restarts~
* [x] Server-side stats https://github.com/elixir-webrtc/apps/pull/11
* [x] Simple chat https://github.com/elixir-webrtc/apps/pull/13

# 0.4.0 (08.2024)

### Website
* [x] A new website https://github.com/elixir-webrtc/elixir-webrtc.github.io/pull/2
* [x] 3 demos deployed 24/h under elixir-webrtc.org https://github.com/elixir-webrtc/apps/pull/23 https://github.com/elixir-webrtc/apps/pull/27 https://github.com/elixir-webrtc/apps/pull/29 https://github.com/elixir-webrtc/apps/pull/30 https://github.com/elixir-webrtc/apps/pull/31 https://github.com/elixir-webrtc/apps/pull/32 https://github.com/elixir-webrtc/apps/pull/37
* [x] Videoroom demo https://github.com/elixir-webrtc/apps/pull/41 https://github.com/elixir-webrtc/apps/pull/25

### Broadcaster
* [x] Chat moderation https://github.com/elixir-webrtc/apps/pull/43 https://github.com/elixir-webrtc/apps/pull/44
* ~Recordings~
* [x] Simulcast https://github.com/elixir-webrtc/apps/pull/22
* [x] https://github.com/elixir-webrtc/apps/issues/34
* [x] https://github.com/elixir-webrtc/apps/issues/35
* [x] https://github.com/elixir-webrtc/apps/issues/36

### ExWebRTC
* [x] Support for all 3 browsers - Chromium/Chrome, Firefox, Safari #127 #149
* [x] ICE fixes - elixir-webrtc/ex_ice#7 elixir-webrtc/ex_ice#19 elixir-webrtc/ex_ice#47 elixir-webrtc/ex_ice#48 elixir-webrtc/ex_ice#49 elixir-webrtc/ex_ice#50 https://github.com/elixir-webrtc/ex_ice/pull/55
* [x] Examples sometimes don't load #132 
* [x] https://github.com/elixir-webrtc/ex_webrtc/issues/137
* [x] https://github.com/elixir-webrtc/ex_webrtc/issues/144

### UX
* [x] ex_webrtc_dashboard - metrics per second #134 elixir-webrtc/ex_webrtc_dashboard#5
* [x] Revisit Xav - https://github.com/elixir-webrtc/xav/compare/v0.4.0...v0.5.0
* [x] Basic tutorials #136 #141
    * I ran echo example but I can't see video
    * What are RTP packets and depayloaders?
    * How to request a keyframe and when to do this?
    * etc.
* [x] https://github.com/elixir-webrtc/ex_webrtc/issues/142
* [x] https://github.com/elixir-webrtc/ex_webrtc/pull/151
* [x] https://github.com/elixir-webrtc/ex_webrtc/issues/143

# 0.5.0 (09.2024)
* [x] DataChannels! :tada: 

# 0.6.0 (10.2024)
* [x] Jitter buffer #158 
* [x] Support for Fly.io #167 #169 

# 0.7.0 (12.2024)

A small, maintenance release. 
* https://github.com/elixir-webrtc/ex_webrtc/pull/176
* [Update deps. Bump version to 0.7.0](https://github.com/elixir-webrtc/ex_webrtc/commit/3fc9cd0ead080f617eaa942852f9be00e30d8e97)

# 0.8.0 (02.2025 - it's 13 months since the first release! 🎉 )
* [x] Track recordings - https://github.com/elixir-webrtc/ex_webrtc/pull/180
* [x] `set_sender_codec/3` and FMTP comparision when negotiating codecs - https://github.com/elixir-webrtc/ex_webrtc/pull/190
* [x] `set_packet_loss/2` - https://github.com/elixir-webrtc/ex_webrtc/pull/182
* [x] SSRC attributes in SDP - https://github.com/elixir-webrtc/ex_webrtc/pull/185
* [x] MID RTP header extension is no longer required - https://github.com/elixir-webrtc/ex_webrtc/commit/d74a93760776461ecb19c0cb8d95fc68ad89cdea 
* [x] A couple of bugfixes -  https://github.com/elixir-webrtc/ex_webrtc/pull/176 https://github.com/elixir-webrtc/ex_webrtc/pull/181 https://github.com/elixir-webrtc/ex_webrtc/pull/184 https://github.com/elixir-webrtc/ex_webrtc/pull/188 https://github.com/elixir-webrtc/ex_webrtc/pull/189

# 0.9.0 (03.2025)
* [x] Track recordings moved to a separate package  ([ex_webrtc_recorder](https://github.com/elixir-webrtc/ex_webrtc_recorder)) - #199 
* [x] Support for VP8 simulcast - #198 
* [x] Ability to specify data_type when using data channels - #200  

# Others
If you have any questions or need help with a specific topic, please create a new [discussion](https://github.com/orgs/elixir-webrtc/discussions)!

* [ ] setParameters on RTPSender
* [ ] Support for AV1 codec, see https://github.com/elixir-webrtc/ex_webrtc/pull/35
* [ ] TCP ICE
* [ ] Support for Windows
* [ ] ex_webrtc_dashboard - performance optimizations
* [ ] bandwidth estimation/probing
* ~~telemetry~~

**Comment by mickel8** [comment]
#33 also adds AV1 to the default video codecs

**Comment by lovebes** [comment]
This is really cool! How would this interact with Membrane Framework?

**Comment by LVala** [comment]
@lovebes at some point we will going to wrap our `ExWebRTC.PeerConnection` in a Membran sink/source, then you'll be able to send/receive media from WebRTC and pass it further into a Membrane pipeline.

**Comment by mickel8** [comment]
Hi @ris-work!
Datachannels are of course on our radar but unfortunately not in 0.2. Maybe in 0.3 or 0.4. But any contributions are welcomed!

**Comment by ris-work** [comment]
> Hi @ris-work! Datachannels are of course on our radar but unfortunately not in 0.2. Maybe in 0.3 or 0.4. But any contributions are welcomed!

Thank you very much for the response! I will be eagerly waiting. Unfortunately, I am neither an expert in WebRTC nor Elixir (or SCTP/RTP), but thank you for considering it for an upcoming version!

**Comment by type1fool** [comment]
I am also excited to see this package developing so quickly.

There are a couple use cases I have in mind that would depend on data channels. For one, it would be cool to deploy gaming app with [elixir-desktop](https://github.com/elixir-desktop/desktop), where two peers could connect directly without an external signaling server.

It's still early in my WebRTC journey, but if I can find time to support implementation, I'd be happy to do so.

**Comment by mickel8** [comment]
Hi guys, support for **DataChannels** just landed in version 0.5.0! We will publish a blog post next week but I wanted to let you know right now :) 

cc @ris-work @type1fool

**Comment by ris-work** [comment]
Thanks @mickel8 and @LVala for this and thanks for the notification! I will start using this soon!

**Comment by mickel8** [comment]
And the blog post on data channels: https://blog.swmansion.com/data-channels-in-elixir-webrtc-0853c7d0e256 :)
